### ISSUE TITLE
DLL Locked by Mathematica

### ISSUE THREAD

**Issue by netlander** [WolframResearch/wolfram-library-link-rs#45]
Have searched around for an answer but haven't found anything useful, here is my problem:
While iterating between Mathematica and the IDE (VS Code in this case) I couldn't go past the first build as Mathematica locks the DLL library so the build fails with this error:

```
fatal error LNK1104: cannot open file 'C:\...\target\debug\deps\hello_cargo.dll'
```
Anyone knows of a workaround other than quitting completely out of Mathematica?
And apologies if this is not the right place..

**Comment by ConnorGray** [comment]
I'm not sure I fully understand the problem, but if the issue is that Windows is preventing the file from being modified because it is open by Mathematica, it might be possible to unlock it by telling Mathematica to unload the library. You can use [`LibraryUnload[..]`](https://reference.wolfram.com/language/ref/LibraryUnload) to unload the library. So in your case, something like:

```wolfram
LibraryUnload["hello_cargo"]
```

(The first argument to `LibraryUnload` should match the library name/path you pass to `LibraryFunctionLoad`.)

Let me know if that helps.

**Comment by netlander** [comment]
Yes that worked! Thanks so much. Closing the issue.
